### ISSUE TITLE
Version 5.3.0

### ISSUE THREAD

**Issue by Siroshun09** [okocraft/Box#194]
### New Player Command: `/box stocklist`

It has the same functionality as `/boxadmin stock list`, but the players can only see their own stock.

### Box Stick: Click on a block to get its item

**This is only available in Minecraft 1.19.4 (or later) because used API is added in that version.**

Hold the Box Stick and click on the block while sneaking to withdraw the block's items from the Box to the main-hand.

The following list gives concrete specifications:

- Box Stick is in the off-hand and the main-hand is empty
  - The item of the clicked block will be withdrawn from Box to the main-hand 
  - Note: This method is already used for depositing/withdrawing items from/to the container, so the item of the container block cannot be deposited
- Box Stick is in the main-hand and the off-hand is empty
  1. Box Stick will be moved to the off-hand
  2. The item of the clicked block will be withdrawn from Box to the main-hand
- Box Stick is in the main-hand and the off-hand is not empty
  1. If the item in the off-hand can not be deposited to Box, nothing to happen
  2. When step 1 is passed, the item in the off-hand will be deposited to Box
  3. Box Stick will be moved to the off-hand
  4. The item of the clicked block will be withdrawn from Box to the main-hand

#### MySQL

MySQL (MariaDB) is now supported as a data storage. 

To use MySQL, configure the following in `config.yml`:

```yaml
storage:
  type: "mysql"
  mysql:
    table-prefix: "box_" # The prefix of the tables
    address: "localhost" # The host of the database
    port: 3306 # The port to connect to the database
    database-name: "box" # The database name (You need to create the database before starting the server)
    username: "" # The username to connect to the database
    password: "" # The password to connect to the database
```

#### Migrator

Added feature to migrate data between different storage types.

For more information, check [wiki page](https://github.com/okocraft/Box/wiki/Storage-Migration) (Japanese).

### API

- `StockHolder#stockDataStream`
- `InventoryTransaction#depositItemsInInventory(Inventory, Predicate)`

## Changes

- Use `sqlite.table-prefix` instead of `database.table_prefix` in `config.yml`
  - `database.table_prefix` is still valid unless `sqlite.table-prefix` is not present
- Delay player data loading to one second after logging in

## Improvements

- Set the initial capacity of the list and reduce the expansion of the list
- Call `InventoryClickEvent` before depositing/withdrawing items from/to the inventory
- Log picking up items to CoreProtect

## Fixes

- Don't set `idleTimeout` to SQLite connection config
- Some fixes and improvements for language files
