### ISSUE TITLE
Release Version 6.0.0

### ISSUE THREAD

**Issue by Siroshun09** [okocraft/Box#336]
### Minecraft 1.20.5 Support

At the same time, Minecraft 1.20.4 or older support has been removed.

### Add a new button to the craft menu for changing the order of ingredient 

[Demo Video](https://imgur.com/a/eeatAOU)

### Deposit items from the player's inventory

In the Box menu, you can deposit items from your inventory by pressing shift + LMB to the item.

[Demo Video](https://imgur.com/a/fUIE3bZ)

### Box requires Java 21

The minimum Java version is updated to Java 21.

### Restructured `config.yml`

Some settings are moved under the `core` section. The `storage` section is the same as v5.

```yml
#
# The core settings of Box.
#
core:
  # Settings related to player stock data.
  stock-data:
    # Number of seconds to unload the player's stock data after logging out.
    unload-time: 300
    # Interval in seconds to save player stock data.
    save-interval: 15
  # The list of worlds where Box cannot be used.
  disabled-worlds: []
  # Whether to enable debug mode or not.
  debug: false
```

- `disabled-features` and `stick.menu-command` has been removed.

### Message format is now MiniMessage

All of the messages have been reformatted using MiniMessage. Also, the default message files have changed to `LOCALE.properties`.

If you are using custom messages, you need to migrate to the new format/file manually.

### Enhanced `categories.yml`

New format:

```yml
dirt:
  disabled: false
  icon: DIRT
  display-name:
    default: Dirt
    ja: 土類
  items: [ ]
```

Most of the settings are migrated automatically. However, the `display-name` of the default category uses the default name.
If you are using custom names for default categories, you need to redefine them. (Before auto-migration, the old `categories.yml` will be copied)

When the Minecraft version is updated, new items are automatically added to the default category. This process is done only once after the update.

### Other Changes

- Box is now [Paper Plugin](https://docs.papermc.io/paper/reference/paper-plugins), so Box is no longer loaded on Bukkit/Spigot completely.
- Experimental items are no longer loaded when the experimental feature is disabled.
- Potion names have been renamed
  - Use Minecraft's potion name instead of Bukkit's one
  - Change extended/upgraded potion names
    - `*_EXTENDED` -> `LONG_*`
    - `*_UPGRADED` -> `STRONG_*`

## API Changes

This changelog only lists changes under `net.okocraft.box.api` package. Other APIs such as feature's API and `storage-api` may have more breaking changes.

### Added API

- [`MCDataVersion#MC_1_20_5`](https://okocraft.github.io/Box/snapshot/net/okocraft/box/api/util/MCDataVersion.html#MC_1_20_5)
- [`ItemVersion`](https://okocraft.github.io/Box/snapshot/net/okocraft/box/api/model/item/ItemVersion.html)
- [`ItemManager#getItemNameConverter`](https://okocraft.github.io/Box/snapshot/net/okocraft/box/api/model/manager/ItemManager.html#getItemNameConverter(net.okocraft.box.api.model.item.ItemVersion))
- Add `EventManager` to `FeatureContext.Registration`
- [`BootstrapContext`](https://okocraft.github.io/Box/snapshot/net/okocraft/box/api/bootstrap/BootstrapContext.html)

### Dependency updates

- ConfigAPI v4 -> v5
- Event4J v3 -> v4

### Newly exposed dependency

- [messages](https://github.com/Siroshun09/messages)

### Removed API

All of the deprecated APIs in v5 have been removed. See #257.

- `ItemImportEvent.ItemType`
- Remove `FeatureProvider` from feature contexts
